trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Pipeline is running"
  displayName: 'Sanity check'

- task: Docker@2
  displayName: 'Build php-fpm image (no push yet)'
  inputs:
    repository: 'mywebapp-php'
    command: 'build'
    Dockerfile: 'docker/php/Dockerfile'
- task: Docker@2
  inputs:
    repository: 'mywebapp-php'
    command: 'build'
    Dockerfile: 'docker/php/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
- task: Docker@2
  displayName: 'Build and push php-fpm image to ACR'
  inputs:
    containerRegistry: 'aztoaz-sc-pipe'
    repository: 'mywebapp-php'
    command: 'buildAndPush'
    Dockerfile: 'docker/php/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(Build.BuildId)
      latest